language: node_js
node_js:
  - 10
branches:
  only:
    - master
script:
  - npm run test
stages:
  - lint
  - test
  - name: release
    if: type != pull_request AND branch = master
jobs:
  include:
    - stage: lint
      script:
        - npm run lint
    - stage: test
      script:
        # Compile JS
        - npm run compile
        # Run integration tests
        - npm run test
    - stage: release
      script:
        - npm install --no-save node-fetch semantic-release
        - npx semantic-release
